name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          registry-url: "https://registry.npmjs.org"
      - name: enable corepack
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
      - name: cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashfiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install modules
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Run lints
        run: yarn lint

      - name: Run formatter
        run: yarn prettier

      - name: Run Build
        run: yarn build
